spring:
  cloud:
    config:
      server:
        accept-empty: true
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          basedir: target/config
          skip-ssl-validation: true
          timeout: 4
          default-label: main
