server:
  port: 8888


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true

logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        accept-empty: true
        git:
          uri: file:/Users/1993heqiang/

---
spring:
  config:
    activate:
      on-profile:
        - cloud

